-- MySQL Script generated by MySQL Workbench
-- Mon May 14 00:30:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `codigoCliente` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `idade` INT NOT NULL,
  `cpf` VARCHAR(100) NOT NULL,
  `status` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`codigoCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Editora` (
  `codigoEditora` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `status` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`codigoEditora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `codigoUsuario` INT NOT NULL,
  `nome` VARCHAR(5) NOT NULL,
  `perfil` VARCHAR(4) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emprestimo` (
  `codigoEmprestimo` INT NOT NULL,
  `saida` DATE NOT NULL,
  `devolucao` DATE NOT NULL,
  `cliente_codigoCliente` INT NOT NULL,
  `funcionario_codigoFuncionario` INT NOT NULL,
  PRIMARY KEY (`codigoEmprestimo`),
  INDEX `fk_Emprestimo_Cliente_idx` (`cliente_codigoCliente` ASC),
  INDEX `fk_Emprestimo_Usuario1_idx` (`funcionario_codigoFuncionario` ASC),
  CONSTRAINT `fk_Emprestimo_Cliente`
    FOREIGN KEY (`cliente_codigoCliente`)
    REFERENCES `mydb`.`Cliente` (`codigoCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Emprestimo_Usuario1`
    FOREIGN KEY (`funcionario_codigoFuncionario`)
    REFERENCES `mydb`.`Usuario` (`codigoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `codigoEstado` INT NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`codigoEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `codigoCidade` INT NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  `estado_codigoEstado` INT NOT NULL,
  PRIMARY KEY (`codigoCidade`),
  INDEX `fk_Cidade_Estado1_idx` (`estado_codigoEstado` ASC),
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`estado_codigoEstado`)
    REFERENCES `mydb`.`Estado` (`codigoEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `codigoCategoria` INT NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`codigoCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Obra` (
  `codigoObra` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `subtitulo` VARCHAR(45) NULL,
  `editora_codigoEditora` INT NOT NULL,
  `cidade_codigoCidade` INT NOT NULL,
  `edicao` VARCHAR(45) NULL,
  `ano` INT NOT NULL,
  `categoria_codigoCategoria` INT NOT NULL,
  `situacao` VARCHAR(15) NOT NULL,
  `status` VARCHAR(12) NOT NULL,
  `codBarras` VARCHAR(50) NULL,
  `qtdEstoqueTotal` INT NOT NULL,
  `qtdEstoqueDisponivel` INT NOT NULL,
  PRIMARY KEY (`codigoObra`),
  INDEX `fk_Obra_Editora1_idx` (`editora_codigoEditora` ASC),
  INDEX `fk_Obra_Cidade1_idx` (`cidade_codigoCidade` ASC),
  INDEX `fk_Obra_Categoria1_idx` (`categoria_codigoCategoria` ASC),
  CONSTRAINT `fk_Obra_Editora1`
    FOREIGN KEY (`editora_codigoEditora`)
    REFERENCES `mydb`.`Editora` (`codigoEditora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Obra_Cidade1`
    FOREIGN KEY (`cidade_codigoCidade`)
    REFERENCES `mydb`.`Cidade` (`codigoCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Obra_Categoria1`
    FOREIGN KEY (`categoria_codigoCategoria`)
    REFERENCES `mydb`.`Categoria` (`codigoCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aux_emprestimo_obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aux_emprestimo_obra` (
  `chegada` DATE NOT NULL,
  `obra_codigoObra` INT NOT NULL,
  `emprestimo_codigoEmprestimo` INT NOT NULL,
  INDEX `fk_aux_emprestimo_obra_Obra1_idx` (`obra_codigoObra` ASC),
  INDEX `fk_aux_emprestimo_obra_Emprestimo1_idx` (`emprestimo_codigoEmprestimo` ASC),
  CONSTRAINT `fk_aux_emprestimo_obra_Obra1`
    FOREIGN KEY (`obra_codigoObra`)
    REFERENCES `mydb`.`Obra` (`codigoObra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aux_emprestimo_obra_Emprestimo1`
    FOREIGN KEY (`emprestimo_codigoEmprestimo`)
    REFERENCES `mydb`.`Emprestimo` (`codigoEmprestimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `codigoAutor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `status` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`codigoAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aux_autor_obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aux_autor_obra` (
  `autor_codigoAutor` INT NOT NULL,
  `obra_ codigoObra` INT NOT NULL,
  INDEX `fk_aux_autor_obra_Obra1_idx` (`obra_ codigoObra` ASC),
  INDEX `fk_aux_autor_obra_Autor1_idx` (`autor_codigoAutor` ASC),
  CONSTRAINT `fk_aux_autor_obra_Obra1`
    FOREIGN KEY (`obra_ codigoObra`)
    REFERENCES `mydb`.`Obra` (`codigoObra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aux_autor_obra_Autor1`
    FOREIGN KEY (`autor_codigoAutor`)
    REFERENCES `mydb`.`Autor` (`codigoAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `codigoEndereco` INT NOT NULL,
  `cliente_codigoCliente` INT NULL,
  `cidade_codigoCidade` INT NOT NULL,
  `editora_codigoEditora` INT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigoEndereco`),
  INDEX `fk_Endereco_Cliente1_idx` (`cliente_codigoCliente` ASC),
  INDEX `fk_Endereco_Cidade1_idx` (`cidade_codigoCidade` ASC),
  INDEX `fk_Endereco_Editora1_idx` (`editora_codigoEditora` ASC),
  CONSTRAINT `fk_Endereco_Cliente1`
    FOREIGN KEY (`cliente_codigoCliente`)
    REFERENCES `mydb`.`Cliente` (`codigoCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Cidade1`
    FOREIGN KEY (`cidade_codigoCidade`)
    REFERENCES `mydb`.`Cidade` (`codigoCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Editora1`
    FOREIGN KEY (`editora_codigoEditora`)
    REFERENCES `mydb`.`Editora` (`codigoEditora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `codigoTelefone` INT NOT NULL,
  `ddd` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `cliente_codigoCliente` INT NULL,
  `editora_codigoEditora` INT NULL,
  PRIMARY KEY (`codigoTelefone`),
  INDEX `fk_Telefone_Cliente1_idx` (`cliente_codigoCliente` ASC),
  INDEX `fk_Telefone_Editora1_idx` (`editora_codigoEditora` ASC),
  CONSTRAINT `fk_Telefone_Cliente1`
    FOREIGN KEY (`cliente_codigoCliente`)
    REFERENCES `mydb`.`Cliente` (`codigoCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefone_Editora1`
    FOREIGN KEY (`editora_codigoEditora`)
    REFERENCES `mydb`.`Editora` (`codigoEditora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`autor` (
  `codigoAutor` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigoAutor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`aux_autor_obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`aux_autor_obra` (
  `codigoAutor` INT(11) NOT NULL,
  `codigoObra` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`aux_emprestimo_obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`aux_emprestimo_obra` (
  `codigoEmprestimo` INT(11) NOT NULL,
  `codigoObra` INT(11) NOT NULL,
  `chegada` DATE NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`categoria` (
  `codigoCategoria` INT(11) NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`codigoCategoria`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`cidade` (
  `codigoCidade` INT(11) NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  `estado_codigoEstado` INT(11) NOT NULL,
  PRIMARY KEY (`codigoCidade`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`cliente` (
  `codigoCliente` INT(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `status` VARCHAR(11) NOT NULL,
  `cpf` VARCHAR(100) NOT NULL,
  `idade` INT(11) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigoCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`editora` (
  `codigoEditora` INT(11) NOT NULL,
  `nomeFantasia` VARCHAR(45) NOT NULL,
  `razaoSocial` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(20) NOT NULL,
  `telefone_codigoTelefone` INT(11) NOT NULL,
  `status` VARCHAR(11) NULL DEFAULT NULL,
  PRIMARY KEY (`codigoEditora`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`emprestimo` (
  `codigoEmprestimo` INT(11) NOT NULL,
  `funcionario_codigoFuncionario` INT(11) NOT NULL,
  `saida` DATE NOT NULL,
  `codigoCliente` INT(11) NOT NULL,
  `devolucao` DATE NOT NULL,
  PRIMARY KEY (`codigoEmprestimo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`endereco` (
  `codigoEndereco` INT(11) NOT NULL,
  `cliente_codigoCliente` INT(11) NULL DEFAULT NULL,
  `cidade_codigoCidade` INT(11) NULL DEFAULT NULL,
  `editora_codigoEditora` INT(11) NULL DEFAULT NULL,
  `rua` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigoEndereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`estado` (
  `codigoEstado` INT(11) NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`codigoEstado`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`obra` (
  `codigoObra` INT(11) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `subtitulo` VARCHAR(50) NULL DEFAULT NULL,
  `editora_codigoEditora` INT(11) NOT NULL,
  `cidade_codigoCidade` INT(11) NULL DEFAULT NULL,
  `edicao` INT(11) NULL DEFAULT NULL,
  `ano` YEAR(4) NOT NULL,
  `categoria_codigoCategoria` INT(11) NOT NULL,
  `situacao` VARCHAR(12) NOT NULL,
  `status` VARCHAR(12) NOT NULL,
  `codBarras` VARCHAR(50) NULL DEFAULT NULL,
  `qtdEstoqueTotal` INT(11) NOT NULL,
  `qtdEstoqueDisponivel` INT(11) NOT NULL,
  PRIMARY KEY (`codigoObra`),
  INDEX `fk_Obra_Editora_idx` (`editora_codigoEditora` ASC),
  CONSTRAINT `fk_Obra_Editora`
    FOREIGN KEY (`editora_codigoEditora`)
    REFERENCES `biblioteca`.`editora` (`codigoEditora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`telefone` (
  `codigoTelefone` INT(11) NOT NULL,
  `ddd` INT(11) NOT NULL,
  `numero` INT(11) NOT NULL,
  `cliente_codigoCliente` INT(11) NULL DEFAULT NULL,
  `editora_codigoEditora` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`codigoTelefone`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`usuario` (
  `codigoUsuario` INT(11) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `perfil` TINYINT(4) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigoUsuario`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
